image: openjdk:17-jdk-alpine




stages:

  - build_deploy




Build and Deploy:

  stage: build_deploy

  script:

    - command -v ssh-agent >/dev/null || (apk add --update openssh)

    - eval $(ssh-agent -s)

    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    - mkdir -p ~/.ssh

    - chmod 700 ~/.ssh

    - ssh-keyscan $EC2_IPADDRESSTRAIN >> ~/.ssh/known_hosts

    - chmod 644 ~/.ssh/known_hosts

    - chmod +x ./gradlew

    - ./gradlew bootJar

    - ls build/libs

    - cp build/libs/IoTDigitalTwin-0.0.1-SNAPSHOT.jar .




    - scp -o StrictHostKeyChecking=no  IoTDigitalTwin-0.0.1-SNAPSHOT.jar ubuntu@$EC2_IPADDRESSTRAIN:/home/ubuntu/HRV/IoTDigitalTwin/build/libs

    - scp -o StrictHostKeyChecking=no docker-compose.yml ubuntu@$EC2_IPADDRESSTRAIN:/home/ubuntu/Allenamenti/IoTDigitalTwin

    - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IPADDRESSTRAIN "cd /home/ubuntu/Allenamenti/IoTDigitalTwin; sudo docker stop mysbaimage-iot-train; sudo docker stop mongodbimage-iot-train; sudo docker compose up"